# Generated by Django 5.0.6 on 2024-06-26 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalisation',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='clinique.salle'),
        ),
    ]
