# Generated by Django 5.0.6 on 2024-06-27 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0003_client_produit_vente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RendezVous',
        ),
    ]
